services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    buildFilter:
      paths:
        - backend/** 